Add vote announcement to voting procedure
openssl/technical-policies pull request #45
Opened 2022-04-25 16:32 UTC by t8m

Simple adjustment of the voting procedure to announce votes via openssl-project ML.

2022-04-26 09:29 UTC, romen requested changes
Collecting some ideas that came up during the OTC discussion of this PR

2022-04-26 09:29 UTC, romen commented on policies/voting-procedure.md
> +All votes governed by this procedure should be announced through an
s/should/must/

2022-04-26 09:29 UTC, romen commented on policies/voting-procedure.md
> +
Add something similar to:

The announcement email must contain a hyperlink to the GitHub issue where the vote is carried out.

2022-04-26 15:11 UTC, t8m commented
Fixup pushed addressing the OTC comments.

2022-05-03 07:54 UTC, romen commented
Last week we did not have consensus about one last item: when closing the vote, should it be also announced on openssl-project?

I'd prefer if we did that.

If it is too much of a burden, should we start looking more concretely into the automation ideas we discussed when we started moving the voting procedures to GitHub?

2022-05-03 11:15 UTC, t8m commented
I feel like there are already too many steps you have to manually do for all the votes. And we already have an internal issue to send notifications for merges to technical-policies and general-policies repos to go into the openssl-project ML.

2022-05-09 16:50 UTC, mspncp commented
Vote: [+1]

2022-05-10 00:05 UTC, paulidale commented
Vote: [+1]

2022-05-10 01:00 UTC, t-j-h commented
Vote: [-1]

Anyone interested in the discussions and decisions around policies should be interacting with the details on github.com and approved policies are on the public website (as links). There is no point in a separate announcement mechanism.

Adding more traffic to openssl-project is not the right move IMHO and in fact there should be less email traffic in general.

2022-05-10 11:59 UTC, beldmit commented
Vote: [-1]

The less manual steps we have, the better are the procedures.

2022-05-17 06:07 UTC, slontis commented
Vote: [+1]

2022-05-17 06:57 UTC, t8m commented
@levitte @kroeckx ping for votes

2022-05-17 19:12 UTC, kroeckx commented
Voting +1

2022-05-18 08:38 UTC, levitte commented
Vote: [+1]

I think that at least for the time being, we need to do this...  Ideally, it would be nice if we only did this on github, but I don't think that everyone is up to speed yet.  This should be revisited in a year or so, and if we decide to change this procedure, it should be announced in the project list some time prior.

2022-05-18 09:29 UTC, t8m commented
Closing the vote.
```
Topic: Add vote announcement to voting procedure at commit 0737de7
       This will become an official OTC policy.
Proposed by: Tomas
Issue link: https://github.com/openssl/technical-policies/pull/45
Public: yes
Opened: 2022-05-09
Closed: 2022-05-18
Accepted:yes    (for: 8, against: 2, abstained: 0, not voted: 0)

   Dmitry     [-1]
   Matt       [+1]
   Pauli      [+1]
   Tim        [-1]
   Richard    [+1]
   Shane      [+1]
   Tomas      [+1]
   Kurt       [+1]
   Matthias   [+1]
   Nicola     [+1]
```

2022-05-18 09:34 UTC, t8m commented
Merged and vote recorded.

2022-05-18 09:34 UTC, closed without merging