Use HTML table for assert table since markdown doesn't render properly
openssl/technical-policies pull request #75
Opened 2023-10-26 20:57 UTC by paulidale

2023-10-30 09:03 UTC, t8m approved these changes

2023-10-30 09:04 UTC, t8m requested changes

2023-10-30 09:04 UTC, t8m commented on policies/coding-style.md
> +    <th>success debug</td>
`s,</td>,</th>,`

2023-10-30 09:23 UTC, paulidale commented on policies/coding-style.md
> +    <th>success debug</td>
Done

2023-10-30 10:35 UTC, t8m approved these changes

2023-11-02 09:12 UTC, mspncp commented
I can't really tell the difference, except that the white-gray shading inside the table is inverted... ?

- **[before](https://github.com/openssl/technical-policies/blob/master/policies/coding-style.md#chapter-16-asserts)**
- **[after](https://github.com/openssl/technical-policies/blob/a5ef24e31632be3e75e7ed9239c3a9721bcbfd67/policies/coding-style.md#chapter-16-asserts)**

2023-11-02 09:17 UTC, mspncp commented
> I can't really tell the difference, except that the white-gray shading inside the table is inverted... ?

If that's the only change, I'm not sure whether it is worth sacrificing the readability of the table in a simple text editor.

2023-11-02 09:19 UTC, mspncp commented
Please forget all I said. I should have looked at https://www.openssl.org/policies/technical/coding-style.html.

2023-11-02 09:25 UTC, mspncp approved these changes

2023-11-06 10:42 UTC, paulidale commented
Merged, thanks for the reviews.

2023-11-06 10:42 UTC, closed without merging

2023-11-06 20:06 UTC, paulidale commented
It's ugly but workable now.
Some further tweaking is possibly required.